### ISSUE TITLE
Buildroot environment

### ISSUE THREAD

**Issue by varadi67** [PerlFFI/FFI-Platypus#395]
I'm using ""Buildroot environment"" HOST architecture "x86-64", TARGET architecture "ARM aarch64"

The probe part stops with an error when you want to run the dlrun program. The completed binary has already been prepared for the TARGET architecture and cannot be run.

How to solve this problem?

**Comment by plicease** [comment]
dlrun is built for the TARGET arch because it needs to probe the settings for the TARGET not the HOST.  I'm not familiar with "buildroot environment" but in Debian (and I am pretty sure other distros) you can use qemu and binfmt to run arm64 on x86_64, which might allow you to run dlrun in the HOST arch.

https://wiki.debian.org/QemuUserEmulation
